### ISSUE TITLE
Browse the application

### ISSUE THREAD

**Issue by LionelJouin** [SEP-G5/Mobile-Client#1]
- Welcome Screen
- Create Key Pair Screen
- Transaction History Screen
- Scan QR Code Screen

**Comment by LionelJouin** [comment]
@bheftye We should modify this to have a more user friendly app:
- Loading screen
  - Check if keys exists, if not create them
  - Check if there are pending transactions and send them
- Welcome page
  - List bikes (Of the user)
  - 2 Buttons, 1 to send the ownership, 1 to receive it
- Send the ownership
  - Camera to scan public key + input for the key (The user can write it manually) + button to go to the next step
  - Generate the transaction, send it and display the QR Code of the transaction
- Receive the ownership
  - Display the QR Code of the public key + button to go to the next step
  - Display last transaction of the public key (to monitor if the sender has already sent the transaction to the blockchain) and scan QR Code, if scanned verify the transaction and send it.
- List of transaction with a search bar

**Comment by bheftye** [comment]
Extended to #27 #28 #29 #30 #31
